######################################################################
#
# File name : tb_wave.do
# Created on: Tue Nov 14 09:36:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
