######################################################################
#
# File name : TOP_wave.do
# Created on: Mon Nov 13 20:35:59 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
